import fs from "fs/promises";
import path from "path";

/**
 * Sentinel-X Genesis Protocol
 * Self-Evolution Engine & Tool Scaffolder
 */
export class GenesisEngine {
	constructor(deps) {
		this.deps = deps;
		this.toolsDir = path.resolve(deps.ROOT_DIR, "sentinel-x/src/tools");
		this.logFile = path.resolve(deps.ROOT_DIR, "sentinel-x/storage/evolution.json");
	}

	async scaffoldTool(name, description, schema, logic) {
		// Basic validation
		if (!/^[a-z0-9_]+$/.test(name)) {
			throw new Error("Tool name must be alphanumeric with underscores.");
		}

		const fileName = `${name}.js`;
		const filePath = path.join(this.toolsDir, fileName);

		const template = `/**
 * Auto-generated by Sentinel-X Genesis Protocol
 * Tool: ${name}
 */

export function definitions() {
	return [
		{
			name: "${name}",
			description: \`${description.replace(/`/g, "\\`")}\`,
			inputSchema: ${JSON.stringify(schema, null, 4).replace(/\n/g, "\n\t\t\t")}
		}
	];
}

export function handlers(deps) {
	return {
		${name}: async (args) => {
			${logic.replace(/\n/g, "\n\t\t\t")}
		}
	};
}
`;

		// Ensure tools dir exists
		await fs.mkdir(this.toolsDir, { recursive: true });
		
		// Write the tool file
		await fs.writeFile(filePath, template, "utf-8");

		// Log the evolution
		await this.logEvolution({ action: "create", tool: name, file: fileName });

		return filePath;
	}

	async logEvolution(entry) {
		let log = { mutations: [] };
		try {
			const data = await fs.readFile(this.logFile, "utf-8");
			log = JSON.parse(data);
		} catch (e) { /* ignore */ }

		log.mutations.push({
			...entry,
			timestamp: new Date().toISOString()
		});

		try {
			await fs.mkdir(path.dirname(this.logFile), { recursive: true });
			await fs.writeFile(this.logFile, JSON.stringify(log, null, 2), "utf-8");
		} catch (e) {
			console.error("[Genesis] Failed to log evolution:", e);
		}
	}

	async getEvolutionLog() {
		try {
			const data = await fs.readFile(this.logFile, "utf-8");
			return JSON.parse(data);
		} catch (e) {
			return { mutations: [] };
		}
	}
}
